# Generated by Django 3.0.3 on 2020-02-28 19:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_personal', models.IntegerField()),
                ('calidad_servicio', models.CharField(choices=[('m', 'Malo'), ('b', 'Bueno'), ('e', 'Excelente')], max_length=10)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
